//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCP_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hcp_apiEntities6 : DbContext
    {
        public hcp_apiEntities6()
            : base("name=hcp_apiEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dependant> dependants { get; set; }
        public DbSet<dependant_fcp> dependant_fcp { get; set; }
        public DbSet<help> helps { get; set; }
        public DbSet<package> packages { get; set; }
        public DbSet<package_fcp> package_fcp { get; set; }
        public DbSet<payment_type> payment_type { get; set; }
        public DbSet<registered> registereds { get; set; }
        public DbSet<registered_fcp> registered_fcp { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserMaster> UserMasters { get; set; }
        public DbSet<help_fcp> help_fcp { get; set; }
        public DbSet<payment_type_fcp> payment_type_fcp { get; set; }
    }
}
