//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCP_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class payment_type
    {
        public payment_type()
        {
            this.registereds = new HashSet<registered>();
        }
    
        public int payment_id { get; set; }
        public string payment { get; set; }
    

        [JsonIgnore]
        public virtual payment_type payment_type1 { get; set; }
        [JsonIgnore]
        public virtual payment_type payment_type2 { get; set; }
        [JsonIgnore]
        public virtual ICollection<registered> registereds { get; set; }
    }
}
